// TypeScript definitions for JetStreamProto WASM bindings
// Auto-generated by wasm-bindgen

/**
 * Delivery mode for streams
 */
export type DeliveryMode = "reliable" | "best_effort";

/**
 * JetStream Connection class
 * 
 * @example
 * ```typescript
 * import { Connection } from 'jetstream-proto';
 * 
 * const conn = new Connection();
 * await conn.connect("ws://localhost:8080");
 * await conn.handshake();
 * 
 * const streamId = await conn.open_stream(1, "reliable");
 * await conn.send(streamId, new Uint8Array([1, 2, 3]));
 * 
 * const packets = await conn.recv();
 * await conn.close();
 * ```
 */
export class Connection {
  /**
   * Create a new Connection instance
   */
  constructor();

  /**
   * Connect to a JetStream server
   * 
   * @param addr - Server address (e.g., "ws://localhost:8080")
   * @returns Promise that resolves when connected
   * @throws Error if connection fails
   */
  connect(addr: string): Promise<void>;

  /**
   * Perform handshake with the server
   * 
   * @returns Promise that resolves with session ID
   */
  handshake(): Promise<number>;

  /**
   * Get the current session ID
   */
  get session_id(): number;

  /**
   * Check if connection is active
   */
  get connected(): boolean;

  /**
   * Open a new stream
   * 
   * @param priority - Stream priority (0-255, higher = more important)
   * @param delivery_mode - Delivery guarantee mode
   * @returns Promise that resolves with stream ID
   * 
   * @example
   * ```typescript
   * const streamId = await conn.open_stream(1, "reliable");
   * ```
   */
  open_stream(priority: number, delivery_mode: DeliveryMode): Promise<number>;

  /**
   * Send data on a stream
   * 
   * @param stream_id - Stream ID to send on
   * @param data - Data to send
   * @returns Promise that resolves when sent
   * 
   * @example
   * ```typescript
   * const data = new TextEncoder().encode("Hello, World!");
   * await conn.send(streamId, data);
   * ```
   */
  send(stream_id: number, data: Uint8Array): Promise<void>;

  /**
   * Receive data from all streams
   * 
   * @returns Promise that resolves with array of [stream_id, data] pairs
   * 
   * @example
   * ```typescript
   * const packets = await conn.recv();
   * for (const [streamId, data] of packets) {
   *   console.log(`Received ${data.length} bytes on stream ${streamId}`);
   * }
   * ```
   */
  recv(): Promise<Array<[number, Uint8Array]>>;

  /**
   * Close the connection gracefully
   * 
   * @returns Promise that resolves when closed
   */
  close(): Promise<void>;
}

/**
 * Initialize the WASM module
 * This is called automatically when the module is loaded
 */
export function init(): void;
